=== apache/nutch/conf/domain-suffixes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<!--
  Document   : domain-suffixes.xsd
  Author     : Enis Soztutar - enis.soz.nutch@gmail.com
  Description: This document is the schema for valid domain-suffixes
  definitions. For successful parsing of domain-suffixes xml files, 
  the xml file should be validated with this xsd. 
  See        : org.apache.nutch.util.domain.DomainSuffixesReader.java
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://lucene.apache.org/nutch"
  xmlns="http://lucene.apache.org/nutch"
  elementFormDefault="qualified">

  <xs:element name="domains">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tlds">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="itlds">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tld" maxOccurs="unbounded"
                      type="gtld" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="gtlds">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tld" maxOccurs="unbounded"
                      type="gtld" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="cctlds">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tld" maxOccurs="unbounded"
                      type="cctld" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="suffixes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="suffix" maxOccurs="unbounded"
                type="sldType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="gtld">
    <xs:sequence>
      <xs:element name="status" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="INFRASTRUCTURE" />
            <xs:enumeration value="SPONSORED" />
            <xs:enumeration value="UNSPONSORED" />
            <xs:enumeration value="STARTUP" />
            <xs:enumeration value="PROPOSED" />
            <xs:enumeration value="DELETED" />
            <xs:enumeration value="PSEUDO_DOMAIN" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="boost" type="xs:float" minOccurs="0" />
      <xs:element name="description" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="domain" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="cctld">
    <xs:sequence>
      <xs:element name="country" type="xs:string" />
      <xs:element name="status" type="statusType" minOccurs="0" />
      <xs:element name="boost" type="xs:float" minOccurs="0" />
      <xs:element name="description" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="domain" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="sldType">
    <xs:sequence>
      <xs:element name="status" type="statusType" minOccurs="0" />
      <xs:element name="boost" type="xs:float" minOccurs="0" />
      <xs:element name="description" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="domain" type="xs:string" />
  </xs:complexType>

  <xs:simpleType name="statusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IN_USE" />
      <xs:enumeration value="NOT_IN_USE" />
      <xs:enumeration value="DELETED" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== apache/nutch/conf/domain-suffixes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<!--
  Document   : domain-suffixes.xml
  Author     : Enis Soztutar - enis.soz.nutch@gmail.com
  Description: This document contains top level domains 
  as described by the Internet Assigned Numbers
  Authotiry (IANA), and second or third level domains that 
  are known to be managed by domain registerers. People at 
  Mozilla community call these public suffixes or effective 
  tlds. There is no algorithmic way of knowing whether a suffix 
  is a public domain suffix, or not. So this large file is used 
  for this purpose. The entries in the file is used to find the
  domain of a url, which may not the same thing as the host of 
  the url. For example for "http://lucene.apache.org/nutch" the 
  hostname is lucene.apache.org, however the domain name for this
  url would be apache.org. Domain names can be quite handy for 
  statistical analysis, and fighting against spam.    
  
  The list of TLDs is constructed from IANA, and the 
  list of "effective tlds" are constructed from Wikipedia, 
  http://wiki.mozilla.org/TLD_List, and http://publicsuffix.org/
  The list may not include all the suffixes, but some
  effort has been spent to make it comprehensive. Please forward 
  any improvements for this list to nutch-dev mailing list, or 
  nutch JIRA. 
  
  Top level domains(tlds) are grouped
  to three, namely infrastrusture, generic and country 
  code tlds. Infrastrusture tlds are only used for 
  technical reasons. Generic tlds represents the type 
  of the organization that they represent. Those in 
  current use and those waiting for approval is listed.
  Most of the country code tlds correspond to the two 
  letter ISO-3166-1 country codes. 
  Each tld is listed with its domain (such as com), a 
  status enumeration describing the status of the tld, 
  and optionally a description or description for convenience.
  cctlds are listed with additional country name field.
  
  status and boost elements are optional, with default values IN_USE 
  and 1.0 respectively. see domain-suffixes.xsd for the xml schema.
  
  
  References : 
  http://www.iana.org
  http://www.iana.org/gtld/gtld.htm
  http://www.iana.org/root-whois/index.html
  http://en.wikipedia.org/wiki/Top-level_domain
  http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
  http://wiki.mozilla.org/TLD_List
  http://publicsuffix.org/
  https://bugzilla.mozilla.org/show_bug.cgi?id=331510
  http://www.neuhaus.com/domaincheck/domain_list.htm
-->

<domains xmlns="http://lucene.apache.org/nutch"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://lucene.apache.org/nutch domain-suffixes.xsd">

  <tlds>
    <!--  Infrastructure Top Level Domains -->
    <itlds>
      <tld domain="root">
        <status>INFRASTRUCTURE</status>
        <description>
          (from http://en.wikipedia.org/wiki/.root)
          vrsn-end-of-zone-marker-dummy-record.root is a domain name
          listed in the DNS root zone as a diagnostic marker, whose
          presence demonstrates the root zone was not truncated upon
          loading by a root nameserver. It could be argued it represents
          a top-level domain of .root, although technically no such
          delegation exists.
        </description>
      </tld>

      <tld domain="arpa">
        <status>INFRASTRUCTURE</status>
        <description>
          (from http://en.wikipedia.org/wiki/.arpa) .arpa is an Internet
          top-level domain (TLD) used exclusively for
          Internet-infrastructure purposes. It does not function as a
          normal TLD where websites are registered, but rather as a
          meta-TLD used to look up addresses, and for other purposes.
        </description>
      </tld>
    </itlds><!--  Generic Top Level Domains -->
    <gtlds>
      <!-- 
        The following gTLDs are in actual use
      -->

      <tld domain="aero">
        <status>SPONSORED</status>
        <description>for the air transport industry</description>
      </tld>

      <tld domain="biz">
        <status>UNSPONSORED</status>
        <description>for business use</description>
      </tld>

      <tld domain="cat">
        <status>SPONSORED</status>
        <description>for Catalan language/culture</description>
      </tld>

      <tld domain="com">
        <status>UNSPONSORED</status>
        <description>
          for commercial organizations, but unrestricted
        </description>
      </tld>

      <tld domain="coop">
        <status>SPONSORED</status>
        <description>for cooperatives</description>
      </tld>

      <tld domain="edu">
        <status>UNSPONSORED</status>
        <boost>1.0</boost>
        <description>
          for post-secondary educational establishments
        </description>
      </tld>

      <tld domain="gov">
        <status>UNSPONSORED</status>
        <description>
          for governments and their agencies in the United States
        </description>
      </tld>

      <tld domain="info">
        <status>UNSPONSORED</status>
        <description>
          for informational sites, but unrestricted
        </description>
      </tld>

      <tld domain="int">
        <status>UNSPONSORED</status>
        <description>
          for international organizations established by treaty
        </description>
      </tld>

      <tld domain="jobs">
        <status>SPONSORED</status>
        <description>for employment-related sites</description>
      </tld>

      <tld domain="mil">
        <status>UNSPONSORED</status>
        <description>for the US military</description>
      </tld>

      <tld domain="mobi">
        <status>SPONSORED</status>
        <description>for sites catering to mobile devices</description>
      </tld>

      <tld domain="museum">
        <status>SPONSORED</status>
        <description>for museums</description>
      </tld>

      <tld domain="name">
        <status>UNSPONSORED</status>
        <description>for families and individuals</description>
      </tld>

      <tld domain="net">
        <status>UNSPONSORED</status>
        <description>
          originally for network infrastructures, now unrestricted
        </description>
      </tld>

      <tld domain="org">
        <status>UNSPONSORED</status>
        <description>
          originally for organizations not clearly falling within the
          other gTLDs, now unrestricted
        </description>
      </tld>

      <tld domain="pro">
        <status>SPONSORED</status>
        <description>for certain professions</description>
      </tld>

      <tld domain="travel">
        <status>SPONSORED</status>
        <description>
          for travel agents, airlines, hoteliers, tourism bureaus, etc.
        </description>
      </tld>

      <!-- 
        The following gTLDs are in the process of being approved, 
        and may be added to the root nameservers in the near future 
      -->

      <tld domain="asia">
        <status>STARTUP</status>
        <description>for the Asian community</description>
      </tld>

      <tld domain="post">
        <status>PROPOSED</status>
        <description>for postal services</description>
      </tld>

      <tld domain="tel">
        <status>STARTUP</status>
        <description>
          for services involving connections between the telephone
          network and the Internet
        </description>
      </tld>

      <tld domain="geo">
        <status>PROPOSED</status>
        <description>for geographically related sites</description>
      </tld>

      <tld domain="gal">
        <status>PROPOSED</status>
        <description>for Galicia, a country within Spain</description>
      </tld>

      <tld domain="cym">
        <status>PROPOSED</status>
        <description>for Wales, a country within the UK</description>
      </tld>

      <tld domain="sco">
        <status>PROPOSED</status>
        <description>for Scotland, a country within the UK</description>
      </tld>

      <tld domain="kid">
        <status>PROPOSED</status>
        <description>for websites designed for children</description>
      </tld>

      <tld domain="kids">
        <status>PROPOSED</status>
        <description>for websites designed for children</description>
      </tld>

      <tld domain="mail">
        <status>PROPOSED</status>
        <description>http://en.wikipedia.org/wiki/.mail</description>
      </tld>

      <tld domain="web">
        <status>PROPOSED</status>
        <description>For Web sites of all sorts</description>
      </tld>

      <tld domain="xxx">
        <status>PROPOSED</status>
        <description>For Adult entertainment sites</description>
      </tld>

      <!-- 
        The following gTLDs are removed from the registry
      -->
      <tld domain="nato">
        <status>DELETED</status>
        <description>
          for NATO sites and operations. Replaced by .int
        </description>
      </tld>

      <!-- 
        The following gTLDs are PSEUDO_DOMAINs
      -->
      <tld domain="bitnet">
        <status>PSEUDO_DOMAIN</status>
        <description>
          identifying a hostname not connected directly to the Internet,
          but a bitnet network
